combine playbooks
Jappie3/flexible-lorawan-architecture pull request #1
Opened 2023-03-30 09:04 UTC by BerrieV1

2023-03-31 07:36 UTC, BerrieV1 commented
combine playbooks

2023-04-03 06:33 UTC, Jappie3 requested changes
looks good, 2 minor fixes needed

2023-04-03 06:33 UTC, Jappie3 commented on ansible/FLWSB-backend-ansible.yaml
> +         update_cache: true
one space too much I think

2023-04-03 06:33 UTC, Jappie3 commented on ansible/FLWSB-backend-ansible.yaml
> +        state: present
add 'become: true'

2023-04-03 06:48 UTC, Jappie3 approved these changes

2023-04-03 07:15 UTC, Jappie3 commented
add nginx & certbot to playbook

2023-04-03 07:16 UTC, merged